services:
  - type: web
    name: interview-tracker
    env: docker
    region: ohio
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
